### PR TITLE
Fix ESLint issues (Errors) - import/named #334

### PR DESCRIPTION
**Pull request by trishnakalita660**

### CODE REVIEW

**Comment by trishnakalita660** [comment]
@jazhen can you review?

**Review by jazhen — COMMENTED** [review]
Hi, I don't think this file needs any changes. The ESLint error was pointing to [wtt_front/client/src/components/Footer/index.js](https://github.com/waterthetrees/wtt_front/blob/main/client/src/components/Footer/index.js).

> 1:10 error default not found in './Footer' import/named

**Comment by trishnakalita660** [comment]
@jazhen  can you review?

**Review by jazhen — APPROVED** [review]
Thanks @trishnakalita660 for contributing!

**Comment by trishnakalita660** [comment]
Hi @jazhen can you please put the labels:  hacktoberfest
hacktoberfest-accepted

**Comment by jazhen** [comment]
@trishnakalita660 - Done

**Comment by trishnakalita660** [comment]
Hi @jazhen can you put hacktoberfest-accepted labels here

**Pull request merged**
